# -*- coding: utf-8 -*-
"""Introducción a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhYqmcuRfPp3GYdTvE_wPgz6QfxaE8IX
"""

import pandas as pd
notas = pd.read_csv("ratings.csv") 
#notas = pd.read_csv("drive/My Drive/Alura/ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioId", "peliculaId", "nota", "momento"]
notas.head()

notas['nota']

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota.head()

notas.nota.plot()

notas.nota.plot(kind='hist')

print("Promedio",notas['nota'].mean())
print("Mediana",notas['nota'].median())

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)