# -*- coding: utf-8 -*-
"""Python para DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNQXp_Dve4L7VK9v6GmmbrRZt1aOJyz3
"""



"""#**Python para DS - Introducción al lenguaje**

"""

import pandas as pd
notas = pd.read_csv('/content/sample_data/ratings.csv')

notas.head()

notas.shape

"""### "shape" me devuelve la estructura de mi conjunto de datos"""

notas.columns=["usuarioId", "peliculaId", "nota", "momento"]

notas.head()

notas.head(10)

notas["nota"]

"""**.unique** devuelve valores unicos"""

notas["nota"].unique()

"""**value_counts** contabiliza cuantas veces se repite cada valor

"""

notas["nota"].value_counts()

notas["nota"].mean()
#devuelve el valor promedio

notas.nota.plot()

notas["nota"].plot(kind="hist")

print("promedio=", notas["nota"].mean())
print("mediana=", notas["nota"].median())

notas.nota.describe()

import seaborn as sns
sns.boxplot(notas.nota)